version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: frontend.dev.Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/var/www/
      - ./frontend:/usr/src/app/
      - ./frontend/node_modules:/usr/src/app/node_modules
      - ./frontend/.next:/usr/src/app/.next
    depends_on:
      - backend
    networks:
      - app

  backend:
    build:
      context: ./backend
      dockerfile: backend.dev.Dockerfile
    restart: always
    # INFO: Mapping breaks node_modules
    volumes:
      - ./backend:/srv/backend
    ports:
      - '1337:1337'
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      DATABASE_SSL: 'false'
    depends_on:
      - mariadb
    networks:
      - app

  mariadb:
    image: mariadb:10.2.7
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    ports:
      - "3306:3306"
    networks:
      - app

networks:
  app:
